name: Delete Failed Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  delete-failed-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete failed workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: .*
          delete_run_by_conclusion_pattern: failure
