name: Delete All Tags

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  delete-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete all tags
        run: |
          # 获取所有标签
          tags=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
               "https://api.github.com/repos/${{ github.repository }}/tags" \
               | jq -r '.[].name')
          
          # 遍历并删除每个标签
          for tag in $tags
          do
            curl -X DELETE -H "Authorization: token ${{ secrets.TOKEN }}" \
                 "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$tag"
            echo "Deleted tag: $tag"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
