name: Delete All Failed Workflows

on:
  workflow_dispatch: # 手动触发

jobs:
  delete_failed_workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List All Failed Workflow Runs
      id: list_failed_workflows
      run: |
        echo "Listing all failed workflow runs..."
        page=1
        failed_runs=""

        while true; do
          # 获取每一页的失败工作流运行
          response=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=failure&per_page=100&page=$page")

          # 检查是否还有更多结果
          count=$(echo "$response" | jq '.workflow_runs | length')
          if [ "$count" -eq "0" ]; then
            break
          fi

          # 获取失败的工作流运行 ID 并追加到 failed_runs 变量
          run_ids=$(echo "$response" | jq -r '.workflow_runs[].id')
          echo "Page $page: Found failed workflow run IDs: $run_ids"
          failed_runs+="$run_ids"$'\n'

          # 下一页
          ((page++))
        done

        if [ -z "$failed_runs" ]; then
          echo "No failed workflow runs found."
          exit 0
        else
          echo "$failed_runs" > failed_workflows.txt
          echo "All failed workflow runs: $failed_runs"
        fi

    - name: Debug: Output failed workflows
      run: cat failed_workflows.txt

    - name: Delete Failed Workflow Runs
      if: success()
      run: |
        echo "Deleting failed workflow runs..."
        while read -r run_id; do
          echo "Deleting workflow run: $run_id"
          response=$(curl -X DELETE -H "Authorization: token ${{ secrets.TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id")

          echo "Response for deleting $run_id: $response"
        done < failed_workflows.txt
