name: Delete All Releases and Tags Except Latest

on:
  workflow_dispatch: # 允许手动触发

jobs:
  clean-up:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch Releases and Tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 获取所有发布版本
        releases=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/owner/repo/releases")

        # 获取所有标签
        tags=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/owner/repo/tags")

        # 获取最新的发布版本 ID
        latest_release_id=$(echo "$releases" | jq -r '.[0].id')

        # 获取最新的标签名称
        latest_tag_name=$(echo "$tags" | jq -r '.[0].name')

        # 删除除最新发布版本之外的所有发布版本
        echo "$releases" | jq -c '.[]' | while IFS= read -r release; do
          release_id=$(echo "$release" | jq -r '.id')
          tag_name=$(echo "$release" | jq -r '.tag_name')
          if [ "$release_id" != "$latest_release_id" ]; then
            echo "Deleting release $tag_name (ID: $release_id)..."
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/owner/repo/releases/$release_id"
          fi
        done

        # 删除除最新标签之外的所有标签
        echo "$tags" | jq -c '.[]' | while IFS= read -r tag; do
          tag_name=$(echo "$tag" | jq -r '.name')
          if [ "$tag_name" != "$latest_tag_name" ]; then
            echo "Deleting tag $tag_name..."
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/owner/repo/git/refs/tags/$tag_name"
          fi
        done
