name: Delete All Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
