name: Delete All Releases and Tags Except Latest

on:
  workflow_dispatch:

jobs:
  clean-up:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch and Delete Old Releases and Tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Fetch all releases with pagination
        releases=""
        page=1
        while true; do
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/greatcoolge/AdBlock_Rule_For_Clash/releases?per_page=100&page=$page")
          releases+="$response"
          [ "$(echo "$response" | jq -r '. | length')" -lt 100 ] && break
          page=$((page + 1))
        done

        # Fetch all tags with pagination
        tags=""
        page=1
        while true; do
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/greatcoolge/AdBlock_Rule_For_Clash/tags?per_page=100&page=$page")
          tags+="$response"
          [ "$(echo "$response" | jq -r '. | length')" -lt 100 ] && break
          page=$((page + 1))
        done

        # Get the latest release ID and tag name
        latest_release_id=$(echo "$releases" | jq -r '.[0].id')
        latest_tag_name=$(echo "$tags" | jq -r '.[0].name')

        # Debugging outputs
        echo "Latest Release ID: $latest_release_id"
        echo "Latest Tag Name: $latest_tag_name"

        # Delete all releases except the latest
        echo "$releases" | jq -c '.[]' | while IFS= read -r release; do
          release_id=$(echo "$release" | jq -r '.id')
          tag_name=$(echo "$release" | jq -r '.tag_name')
          if [ "$release_id" != "$latest_release_id" ]; then
            echo "Deleting release $tag_name (ID: $release_id)..."
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/greatcoolge/AdBlock_Rule_For_Clash/releases/$release_id"
          fi
        done

        # Delete all tags except the latest
        echo "$tags" | jq -c '.[]' | while IFS= read -r tag; do
          tag_name=$(echo "$tag" | jq -r '.name')
          if [ "$tag_name" != "$latest_tag_name" ]; then
            echo "Deleting tag $tag_name..."
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/greatcoolge/AdBlock_Rule_For_Clash/git/refs/tags/$tag_name"
          fi
        done
